import { headers } from 'next/headers';
import { auth } from '@/lib/auth';
import sql from '@/app/api/utils/sql';
import { getAIIntegrationUrl } from '@/app/api/utils/ai';

function safeParseJSON(raw: string) {
  let text = raw.trim();
  const fenceMatch = text.match(/^```(?:json|typescript|ts)?\n?([\s\S]*?)```$/);
  if (fenceMatch) text = fenceMatch[1].trim();
  return JSON.parse(text);
}

function parseSteps(raw: unknown): string[] {
  try {
    const parsed = typeof raw === 'string' ? JSON.parse(raw) : raw;
    if (!Array.isArray(parsed)) return [];
    return parsed.map((s) =>
      typeof s === 'string' ? s : s.step || s.action || s.description || JSON.stringify(s)
    );
  } catch {
    return typeof raw === 'string' ? [raw] : [];
  }
}

function escapeStr(s: string): string {
  return (s || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").substring(0, 120);
}

function buildTemplateTest(tc: Record<string, unknown>, steps: string[], baseUrl: string): string {
  const lines: string[] = [
    `  test('${tc.test_case_id}: ${escapeStr(String(tc.title || ''))}', async ({ page }) => {`,
    `    // Type: ${tc.test_type} | Priority: ${tc.priority}`,
    `    // Scenario: ${String(tc.test_scenario || '').substring(0, 200)}`,
  ];

  if (tc.preconditions) {
    lines.push(`    // Preconditions: ${String(tc.preconditions).substring(0, 200)}`);
  }

  lines.push(`    await page.goto('${baseUrl}');`);

  steps.forEach((step, i) => {
    const lower = step.toLowerCase();
    lines.push(`    // Step ${i + 1}: ${step}`);
    if (lower.includes('click')) {
      lines.push(`    // await page.getByRole('button', { name: '...' }).click();`);
    } else if (lower.includes('enter') || lower.includes('type') || lower.includes('fill')) {
      lines.push(`    // await page.getByLabel('...').fill('...');`);
    } else if (lower.includes('navigate') || lower.includes('go to')) {
      lines.push(`    // await page.goto('/path');`);
    } else if (lower.includes('verify') || lower.includes('check') || lower.includes('assert')) {
      lines.push(`    // await expect(page.getByText('...')).toBeVisible();`);
    } else {
      lines.push(`    // await page.locator('[data-testid="element"]').click();`);
    }
  });

  lines.push(`    // Expected: ${String(tc.expected_result || '').substring(0, 200)}`);
  lines.push(`    await expect(page).not.toHaveURL('about:blank');`);
  lines.push(`  });`);
  return lines.join('\n');
}

function assembleSpec(
  projectName: string,
  runName: string,
  baseUrl: string,
  tests: string[]
): string {
  const today = new Date().toISOString().split('T')[0];
  return [
    "import { test, expect } from '@playwright/test';",
    '',
    `// Project: ${projectName}`,
    `// Test Run: ${runName}`,
    `// Base URL: ${baseUrl}`,
    `// Generated by QA Copilot on ${today}`,
    `// Total Tests: ${tests.length}`,
    '',
    `test.describe('${escapeStr(runName)}', () => {`,
    '',
    '  test.beforeEach(async ({ page }) => {',
    '    await page.setViewportSize({ width: 1280, height: 720 });',
    '  });',
    '',
    tests.join('\n\n'),
    '',
    '});',
  ].join('\n');
}

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const { id } = await params;
  const body = await request.json().catch(() => ({}));
  const baseUrl: string = (body.base_url || 'https://your-app-url.com').replace(/\/$/, '');

  try {
    const runRows = await sql`
      SELECT tr.*, p.name as project_name
      FROM test_runs tr
      JOIN projects p ON tr.project_id = p.id
      WHERE tr.id = ${id} AND p.created_by = ${session.user.id}
    `;
    if (!runRows[0]) return Response.json({ error: 'Test run not found' }, { status: 404 });
    const run = runRows[0];

    let testCases: Record<string, unknown>[];
    if (run.test_suite_id) {
      testCases = await sql`
        SELECT tc.* FROM test_cases tc
        JOIN test_suite_cases tsc ON tsc.test_case_id = tc.id
        WHERE tsc.test_suite_id = ${run.test_suite_id}
        ORDER BY tsc.execution_order ASC LIMIT 50
      `;
    } else {
      testCases = await sql`
        SELECT * FROM test_cases WHERE project_id = ${run.project_id}
        ORDER BY created_at ASC LIMIT 50
      `;
    }

    if (testCases.length === 0) {
      return Response.json({ error: 'No test cases found for this run' }, { status: 400 });
    }

    const caseData = testCases.map((tc) => ({ tc, steps: parseSteps(tc.test_steps) }));

    // ── Single batched AI call for all test cases ──────────────
    const integrationUrl = getAIIntegrationUrl();

    let aiTestBlocks: Record<string, string> = {};

    try {
      const caseSummaries = caseData.slice(0, 20).map(({ tc, steps }) => ({
        id: String(tc.test_case_id || ''),
        title: String(tc.title || '').substring(0, 80),
        type: tc.test_type,
        scenario: String(tc.test_scenario || '').substring(0, 120),
        steps: steps.slice(0, 8),
        expected: String(tc.expected_result || '').substring(0, 120),
      }));

      const promptLines = [
        'You are a Playwright TypeScript expert.',
        'Convert the following test cases into Playwright test body code (the code inside test(async ({ page }) => { HERE })).',
        '',
        'Base URL: ' + baseUrl,
        '',
        'Rules:',
        '- Use page.goto, page.click, page.fill, expect() assertions',
        '- Use getByRole, getByLabel, getByText, getByPlaceholder selectors where possible',
        '- Add a short comment per step',
        '- Keep each test under 20 lines',
        '- Use placeholder selectors like page.locator(\'[data-testid="submit"]\') if the real selector is unknown',
        '',
        'Return ONLY a raw JSON object (no markdown, no explanation):',
        '{"tests":{"TC-0001":"await page.goto(...);\\n// step 1","TC-0002":"..."}}',
        '',
        'Test cases to convert:',
        JSON.stringify(caseSummaries),
      ];
      const prompt = promptLines.join('\n');

      const aiRes = await fetch(integrationUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${process.env.ANYTHING_PROJECT_TOKEN}`,
        },
        body: JSON.stringify({
          messages: [{ role: 'user', content: prompt }],
        }),
      });

      if (aiRes.ok) {
        const aiData = await aiRes.json();
        const raw: string = aiData.choices?.[0]?.message?.content || '';
        console.log('[playwright] AI raw (first 200):', raw.slice(0, 200));
        const parsed = safeParseJSON(raw);
        if (parsed && typeof parsed.tests === 'object') {
          aiTestBlocks = parsed.tests;
        }
      } else {
        const errText = await aiRes.text().catch(() => '');
        console.error('[playwright] AI call failed:', aiRes.status, errText.slice(0, 200));
      }
    } catch (aiErr) {
      console.error('[playwright] AI error, using templates:', aiErr);
    }

    const aiCount = Object.keys(aiTestBlocks).length;
    console.log('[playwright] AI generated', aiCount, 'of', caseData.length, 'test blocks');

    // ── Build final test blocks ────────────────────────────────
    const generatedTests: string[] = caseData.map(({ tc, steps }) => {
      const tcId = String(tc.test_case_id || '');
      const aiCode = aiTestBlocks[tcId];

      if (aiCode && aiCode.trim().length > 10) {
        const indented = aiCode
          .split('\n')
          .map((l) => '    ' + l)
          .join('\n');
        return [
          "  test('" + tcId + ': ' + escapeStr(String(tc.title || '')) + "', async ({ page }) => {",
          indented,
          '  });',
        ].join('\n');
      }

      return buildTemplateTest(tc, steps, baseUrl);
    });

    const specFile = assembleSpec(run.project_name, run.name, baseUrl, generatedTests);

    const packageJson = JSON.stringify(
      {
        name: 'qa-copilot-tests',
        version: '1.0.0',
        scripts: {
          test: 'playwright test',
          'test:headed': 'playwright test --headed',
          'test:ui': 'playwright test --ui',
          'test:report': 'playwright show-report',
        },
        devDependencies: {
          '@playwright/test': '^1.44.0',
          typescript: '^5.4.0',
        },
      },
      null,
      2
    );

    const today = new Date().toISOString().split('T')[0];

    const configLines = [
      "import { defineConfig, devices } from '@playwright/test';",
      '',
      'export default defineConfig({',
      "  testDir: './tests',",
      '  timeout: 30000,',
      '  expect: { timeout: 5000 },',
      '  fullyParallel: false,',
      '  retries: 1,',
      "  reporter: [['html'], ['list']],",
      '  use: {',
      "    baseURL: '" + baseUrl + "',",
      "    trace: 'on-first-retry',",
      "    screenshot: 'only-on-failure',",
      "    video: 'on-first-retry',",
      '  },',
      '  projects: [',
      "    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },",
      "    { name: 'firefox',  use: { ...devices['Desktop Firefox'] } },",
      '  ],',
      '});',
    ];
    const playwrightConfig = configLines.join('\n');

    const readmeLines = [
      '# QA Copilot — Generated Playwright Tests',
      '',
      '**Project:** ' + run.project_name,
      '**Test Run:** ' + run.name,
      '**Generated:** ' + today,
      '**Total Tests:** ' + testCases.length,
      '**AI-Generated:** ' + aiCount + ' / ' + testCases.length + ' tests',
      '**App URL:** ' + baseUrl,
      '',
      '## Quick Start',
      '',
      '```bash',
      'npm install',
      'npx playwright install',
      'npx playwright test',
      '```',
      '',
      '## Other Commands',
      '```bash',
      '# Run with visible browser',
      'npm run test:headed',
      '',
      '# Interactive UI mode',
      'npm run test:ui',
      '',
      '# View HTML report',
      'npm run test:report',
      '```',
      '',
      '## GitHub Actions CI/CD',
      '```yaml',
      'name: Playwright Tests',
      'on: [push, pull_request]',
      'jobs:',
      '  test:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: actions/setup-node@v4',
      '        with: { node-version: 20 }',
      '      - run: npm install',
      '      - run: npx playwright install --with-deps',
      '      - run: npx playwright test',
      '      - uses: actions/upload-artifact@v4',
      '        if: always()',
      '        with:',
      '          name: playwright-report',
      '          path: playwright-report/',
      '```',
    ];
    const readme = readmeLines.join('\n');

    return Response.json({
      success: true,
      test_count: testCases.length,
      ai_generated: aiCount,
      files: {
        'tests/generated.spec.ts': specFile,
        'playwright.config.ts': playwrightConfig,
        'package.json': packageJson,
        'README.md': readme,
      },
    });
  } catch (error) {
    console.error('[playwright] Unexpected error:', error);
    return Response.json(
      { error: error instanceof Error ? error.message : 'Failed to generate scripts' },
      { status: 500 }
    );
  }
}
